// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: scorereader.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

public static partial class ScoreReader
{
  static readonly string __ServiceName = "ScoreReader";

  static readonly grpc::Marshaller<global::ScoreRequest> __Marshaller_ScoreRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::ScoreRequest.Parser.ParseFrom);
  static readonly grpc::Marshaller<global::ScoreResponse> __Marshaller_ScoreResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::ScoreResponse.Parser.ParseFrom);

  static readonly grpc::Method<global::ScoreRequest, global::ScoreResponse> __Method_Read = new grpc::Method<global::ScoreRequest, global::ScoreResponse>(
      grpc::MethodType.Unary,
      __ServiceName,
      "Read",
      __Marshaller_ScoreRequest,
      __Marshaller_ScoreResponse);

  /// <summary>Service descriptor</summary>
  public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
  {
    get { return global::ScorereaderReflection.Descriptor.Services[0]; }
  }

  /// <summary>Base class for server-side implementations of ScoreReader</summary>
  public abstract partial class ScoreReaderBase
  {
    public virtual global::System.Threading.Tasks.Task<global::ScoreResponse> Read(global::ScoreRequest request, grpc::ServerCallContext context)
    {
      throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
    }

  }

  /// <summary>Client for ScoreReader</summary>
  public partial class ScoreReaderClient : grpc::ClientBase<ScoreReaderClient>
  {
    /// <summary>Creates a new client for ScoreReader</summary>
    /// <param name="channel">The channel to use to make remote calls.</param>
    public ScoreReaderClient(grpc::Channel channel) : base(channel)
    {
    }
    /// <summary>Creates a new client for ScoreReader that uses a custom <c>CallInvoker</c>.</summary>
    /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
    public ScoreReaderClient(grpc::CallInvoker callInvoker) : base(callInvoker)
    {
    }
    /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
    protected ScoreReaderClient() : base()
    {
    }
    /// <summary>Protected constructor to allow creation of configured clients.</summary>
    /// <param name="configuration">The client configuration.</param>
    protected ScoreReaderClient(ClientBaseConfiguration configuration) : base(configuration)
    {
    }

    public virtual global::ScoreResponse Read(global::ScoreRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return Read(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual global::ScoreResponse Read(global::ScoreRequest request, grpc::CallOptions options)
    {
      return CallInvoker.BlockingUnaryCall(__Method_Read, null, options, request);
    }
    public virtual grpc::AsyncUnaryCall<global::ScoreResponse> ReadAsync(global::ScoreRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return ReadAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual grpc::AsyncUnaryCall<global::ScoreResponse> ReadAsync(global::ScoreRequest request, grpc::CallOptions options)
    {
      return CallInvoker.AsyncUnaryCall(__Method_Read, null, options, request);
    }
    /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
    protected override ScoreReaderClient NewInstance(ClientBaseConfiguration configuration)
    {
      return new ScoreReaderClient(configuration);
    }
  }

  /// <summary>Creates service definition that can be registered with a server</summary>
  /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
  public static grpc::ServerServiceDefinition BindService(ScoreReaderBase serviceImpl)
  {
    return grpc::ServerServiceDefinition.CreateBuilder()
        .AddMethod(__Method_Read, serviceImpl.Read).Build();
  }

}
#endregion
