# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import scorereader_pb2 as scorereader__pb2


class ScoreReaderStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Read = channel.unary_unary(
        '/ScoreReader/Read',
        request_serializer=scorereader__pb2.ScoreRequest.SerializeToString,
        response_deserializer=scorereader__pb2.ScoreResponse.FromString,
        )


class ScoreReaderServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Read(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ScoreReaderServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Read': grpc.unary_unary_rpc_method_handler(
          servicer.Read,
          request_deserializer=scorereader__pb2.ScoreRequest.FromString,
          response_serializer=scorereader__pb2.ScoreResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ScoreReader', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
