# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scorereader.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='scorereader.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11scorereader.proto\" \n\x0cScoreRequest\x12\x10\n\x08sourceid\x18\x01 \x01(\t\"\x1d\n\rScoreResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t24\n\x0bScoreReader\x12%\n\x04Read\x12\r.ScoreRequest\x1a\x0e.ScoreResponseb\x06proto3')
)




_SCOREREQUEST = _descriptor.Descriptor(
  name='ScoreRequest',
  full_name='ScoreRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sourceid', full_name='ScoreRequest.sourceid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=53,
)


_SCORERESPONSE = _descriptor.Descriptor(
  name='ScoreResponse',
  full_name='ScoreResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='ScoreResponse.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=84,
)

DESCRIPTOR.message_types_by_name['ScoreRequest'] = _SCOREREQUEST
DESCRIPTOR.message_types_by_name['ScoreResponse'] = _SCORERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ScoreRequest = _reflection.GeneratedProtocolMessageType('ScoreRequest', (_message.Message,), dict(
  DESCRIPTOR = _SCOREREQUEST,
  __module__ = 'scorereader_pb2'
  # @@protoc_insertion_point(class_scope:ScoreRequest)
  ))
_sym_db.RegisterMessage(ScoreRequest)

ScoreResponse = _reflection.GeneratedProtocolMessageType('ScoreResponse', (_message.Message,), dict(
  DESCRIPTOR = _SCORERESPONSE,
  __module__ = 'scorereader_pb2'
  # @@protoc_insertion_point(class_scope:ScoreResponse)
  ))
_sym_db.RegisterMessage(ScoreResponse)



_SCOREREADER = _descriptor.ServiceDescriptor(
  name='ScoreReader',
  full_name='ScoreReader',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=86,
  serialized_end=138,
  methods=[
  _descriptor.MethodDescriptor(
    name='Read',
    full_name='ScoreReader.Read',
    index=0,
    containing_service=None,
    input_type=_SCOREREQUEST,
    output_type=_SCORERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SCOREREADER)

DESCRIPTOR.services_by_name['ScoreReader'] = _SCOREREADER

# @@protoc_insertion_point(module_scope)
